### ISSUE TITLE
[Bug]: Workspaces + container tabs are broken

### ISSUE THREAD

**Issue by stdStudent** [Floorp-Projects/Floorp#1337]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

New tabs in a specified workspace doesn't open in a specified container group. Moreover, containers created by users are shown as undefined in the workspace settings. 

### Reproduction Steps

1. Update Floorp to the version 11.17.1
2. Try opening a tab in a workspace

### Expected Behavior

A tab must be opened in a specified container group. 

### Actual Behavior

A tab is opened in a default group. 

### Screenshots

![image](https://github.com/user-attachments/assets/bc129c72-2567-47c7-8505-bec17bb49cd2)

### Browser Version

11.17.1

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
I reproduce this bug. This issue will be fixed  at 11.17.4

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/f69d051a-14b4-4031-a02e-f4f9d87e6ecd)
I found a fix. Wauting for next update

**Comment by surapunoyousei** [comment]
Fixed

**Comment by stdStudent** [comment]
Thank you for a timely fix!

**Comment by Beryesa** [comment]
It's still broken on the latest version, can't set the default container for the workspace and new workspaces keep getting deleted 🤔 
Should I create a new issue?

**Comment by stdStudent** [comment]
@Beryesa, I got my problem fixed with the 11.17.4 update. Sounds like you have a different issue, so you might want to create a new issue.

**Comment by villainous-j** [comment]
yeah i'm having the same issue as Beryesa, will try to report it.
