### ISSUE TITLE
[Bug]:Customize toolbar browser goes transparent.

### ISSUE THREAD

**Issue by jonzn4suse** [Floorp-Projects/Floorp#1437]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When trying to customize the toolbar, the browser goes transparent.  I have Floorp running on 1 Leap and 3 Tumbleweed  laptops and can reproduce the issue on all of them.

### Reproduction Steps

Try to customize toolbar

### Expected Behavior

Should see options to customize toolbar
![ESR_Screenshot_20240915_100333](https://github.com/user-attachments/assets/a9d61286-e5e6-4030-a7fa-a205ac17bd2a)

### Actual Behavior

Browser goes transparent and cannot see anything.
![floorp issue_Screenshot_20240915_095837](https://github.com/user-attachments/assets/5e27db66-b42c-431c-86c7-9df0bf926772)

### Screenshots

![floorp issue_Screenshot_20240915_095837](https://github.com/user-attachments/assets/e60043c4-5eb5-4b8b-ac1f-c8296ec58326)
![ESR_Screenshot_20240915_100333](https://github.com/user-attachments/assets/45b70b78-3d33-4582-8189-7c889867ca30)

### Browser Version

11.18.1 (64-bit)

### Operating System

openSUSE Leap 15.6

### Additional Context

Operating System: openSUSE Leap 15.6
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.4.0-150600.23.17-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 PRO 6850HS with Radeon Graphics
Memory: 62.1 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: HP
Product Name: HP EliteBook 865 16 inch G9 Notebook PC
System Version: SBKPF

**Comment by surapunoyousei** [comment]
Do you use Flatpak version of Floorp?

**Comment by jonzn4suse** [comment]
Just downloaded from the site and run from the folder.

**Comment by jonzn4suse** [comment]
Here's another computer.
![floorp on 455_Screenshot_20240915_192310](https://github.com/user-attachments/assets/f2cbe437-a4ba-48ef-9884-0c3391c0af30)

**Comment by creeper-0910** [comment]
If I run "MOZ_ENABLE_WAYLAND=0 floorp", does it work correctly?

**Comment by jonzn4suse** [comment]
Updated browser and variable, but no joy. 
![floorp_Screenshot_20240917_185912](https://github.com/user-attachments/assets/fe361a60-6d5b-400a-bd21-de5717b35d7a)

**Comment by henlo-birb** [comment]
I have the same issue, for some reason enabling the title bar fixes it. I'm guessing there's some bug in the wayland code that lets it display the system window close/maximize buttons on top of the window when the title bar is disabled.

**Comment by creeper-0910** [comment]
I thought so too, but I don't know the cause as it also occurs when wayland is disabled...

**Comment by jonzn4suse** [comment]
> I have the same issue, for some reason enabling the title bar fixes it. I'm guessing there's some bug in the wayland code that lets it display the system window close/maximize buttons on top of the window when the title bar is disabled and you're editing the title bar, since that's the thing that could require transparency.

A screenshot would be helpful.

**Comment by ProneelPal** [comment]
In my experience, this happens if you have Photon/Lepton UI. The problem solved in Proton UI or Floorp Fluerial UI.

**Comment by jonzn4suse** [comment]
Just updated to 11.20.0, still no joy.

**Comment by opensourcer2** [comment]
I don't use wayland (Linux Mint 21) and I still have this same problem.

**Comment by opensourcer2** [comment]
Not planned? This is a bug, not a feature request.

**Comment by robeecodes** [comment]
I'm on Pop!_OS using X11 and came across this today. Adding the following to my userChrome.css helped:

```css
@media (-moz-bool-pref: "userChrome.compatibility.theme") {
    #customization-container {
        background-color: rgb(13, 13, 16) !important;
    }
    #statusBar {
        background-color: rgb(13, 13, 16) !important;
    }
}

**Comment by JSGRD22** [comment]
Same problem here. Is this issue resolved in v12 for anyone? I can put up with it for a while longer if the upgrade fixes it once and for all.

**Comment by cotton105** [comment]
I'm no longer seeing this problem, using v12.6.0 on Wayland (Lepton UI).

<img width="2561" height="1395" alt="Image" src="https://github.com/user-attachments/assets/d758c710-cf9a-470f-b3b1-27be54c020ce" />

**Comment by jonzn4suse** [comment]
Yes, just checked and it works.

Operating System: openSUSE Tumbleweed 20251125
KDE Plasma Version: 6.5.3
KDE Frameworks Version: 6.20.0
Qt Version: 6.10.1
Kernel Version: 6.17.8-2-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5825U with Radeon Graphics
Memory: 64 GiB of RAM (62.1 GiB usable)
Graphics Processor: AMD Radeon Graphics
Manufacturer: HP
Product Name: HP ProBook 455 15.6 inch G9 Notebook PC

**Comment by jonzn4suse** [comment]
There was another issue where I couldn't update via the normal help and about.  Cloudflare is blocking ablaze.com.
Had to download another ball, but the help and about update check works in the current version.
