### ISSUE TITLE
[Bug]: "Undo Closed Tab" button cannot remove from toolbar

### ISSUE THREAD

**Issue by alrcatraz** [Floorp-Projects/Floorp#1745]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp can customise toolbar, but if `Undo Closed Tab` button was removed from toolbar, everytime the Floorp is restarted, it will repair in its default position.

### Reproduction Steps

1. Open Floorp
2. Right click at tool bar, choose 'customise toolbar'
3. Remove `Undo Closed Tab` button
4. Close Floorp (or restart computer)
5. Open Floorp
6. The button will show at its initial position

### Expected Behavior

the `Undo Closed Tab` button should not show up after remove it from toolbar

### Actual Behavior

the button will show up every time Floorp is restarted

### Screenshots

![Image](https://github.com/user-attachments/assets/28040d26-4a66-4be0-b106-8cb252cba203)

### Browser Version

139.0@12.0.2

### Operating System

Windows 11 Pro

**Comment by moriel5** [comment]
I can confirm that this is also the case on Linux.
I can move the button elsewhere, and it's placement will persist (it used to be that even that was not the case), however without disabling it from about:config (under the noraneko features), it will return to it's default location if removed.

**Comment by ioc2e3** [comment]
> Floorp 可以自訂工具列，但如果`Undo Closed Tab`按鈕從工具列中刪除，每次重新啟動 Floorp 時，它都會修復到其預設位置。

This is also the case on Win 10 ...

.

**Comment by absol-0359** [comment]
This issue appears to have been fixed in 140.0@12.0.4 and later (the current latest version is 140.0@12.0.5).
Please try updating.

**Comment by alrcatraz** [comment]
> This issue appears to have been fixed in 140.0@12.0.4 and later (the current latest version is 140.0@12.0.5). Please try updating.

I tried update to 12.0.4 yesterday, but floorp cannot start, and just now I tried to update to 12.0.5, but the browser window still cannot show up.

**Comment by Ryosuke-Asano** [comment]
Fixed!
