### ISSUE TITLE
[Bug]: userChrome.css does not appear to load on v12 but does on Firefox v139 and Floorp v11

### ISSUE THREAD

**Issue by FGD-Garuda** [Floorp-Projects/Floorp#1754]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

`userChrome.css` file does not appear to load under Floorp 12.
Same file does load using Floorp 11.
Same file does load using Firefox v139, which if I recall correctly is Floorp 12's base.

Testing on multiple machines returns same behavior.
Testing with a new profile returns same behavior.

### Reproduction Steps

1. Install latest Floorp 12
2. Make sure a new Profile is created
3. Launch Floorp 12
4. Go in `about:config` and ensure `toolkit.legacyUserProfileCustomizations.stylesheets` is set to `TRUE`
5. Close Floorp 12
6. Copy a simple `userChrome.css `that works on many Firefox and Floorp versions in `$HOME/.floorp/$PROFILE/chrome/`
~~~
#urlbar-background,
#urlbar-input-container {
  background-color: blue !important;
}

#urlbar-background #urlbar-input {
  background-color: blue !important;
}
~~~
7. Launch Floorp 12.

### Expected Behavior

`userChrome.css` should be loaded and apply the UI style, in this example it would turn the URLBAR blue.

### Actual Behavior

No UI change.

### Screenshots

FLOORP 11
![Image](https://github.com/user-attachments/assets/0340904a-eba3-4d30-96b0-52ec0f55e9f0)

FIREFOX 139
![Image](https://github.com/user-attachments/assets/04bab477-156a-48f2-9f6a-f04d4fe990a6)

FLOORP 12
![Image](https://github.com/user-attachments/assets/8eaa07af-361f-4827-873b-951f2c6749e4)

### Browser Version

12

### Operating System

Linux

**Comment by Mingo-coder** [comment]
Happened to mine on windows 11 as well. None of my css worked so I am using waterfox meanwhile. 

Another strange thing that happened is Container Tab is no longer showing...I had a lot of container tabs opened before the update and then all my tabs were gone after updating to v12. Again I haven't faced this issue with waterfox. 

Also posted a performance issue bug i faced in floorp only but it was closed as not planned. I really had high hopes for this browser.

**Comment by FGD-Garuda** [comment]
Thanks for confirming someone else gets the issue as well!

**Comment by Ryosuke-Asano** [comment]
Since Floorp 12 is being built on an entirely new foundation, we have closed all existing issues and retained only those related to Floorp 12. We sincerely apologize for this.

This particular issue has been confirmed, and we are currently preparing an update due to a problem in the Lepton implementation. Thank you for your patience.

**Comment by FGD-Garuda** [comment]
Excellent, thank you very much!

**Comment by Ryosuke-Asano** [comment]
Fixed!

**Comment by stefanwimmer128** [comment]
Could you please confirm which commit(s) fix this issue, so I can make sure that those are correctly merged in FireDragon?

**Comment by Ryosuke-Asano** [comment]
https://github.com/Floorp-Projects/Floorp/commit/de7c4d8bf33f0b26347354d33e2da58ea14c9e26

I’m truly sorry for the inconvenience caused to the fork due to my recent busyness with the development of other Floorp-related products and university work.

Thank you for your understanding.

**Comment by stefanwimmer128** [comment]
Thanks for the info. And no problem, I completely understand being busy with work.

So just to check, the 12.0.4 release should already have the fix? Because the tag seems to be wrongly pointing to the old ESR128 branch: https://github.com/Floorp-Projects/Floorp/commits/v12.0.4/.

**Comment by FGD-Garuda** [comment]
I'm sorry, I still cannot make `userChrome.css` to work at all.
Is there something in the required steps (see OP) that I am doing wrong or missing?

I am also trying to see whether the commit is included in v12.0.5, but with a [compare between 12.0.0 and 12.0.5](https://github.com/Floorp-Projects/Floorp/compare/v12.0.0...v12.0.5) I cannot find it in the list. Possible I am not looking properly but in the end I still cannot make CSS to work.

**Comment by Ryosuke-Asano** [comment]
Everyone, it seems that the feature works in the development environment, but there are cases where it doesn't work in the production environment. I will investigate further, so please bear with me.

**Comment by Ryosuke-Asano** [comment]
Fixed!

**Comment by FGD-Garuda** [comment]
It is!
12.0.13 and up are working.

Thank you!

**Comment by stefanwimmer128** [comment]
Thanks for the fix. Can you please point me to the required fix, since after merging all latest changes we still get this error in FireDragon?

**Comment by Ryosuke-Asano** [comment]
https://github.com/Floorp-Projects/Floorp/tree/main/gecko/pref

By using this script to enable the userChrome.css settings by default.You can resolve this by using this script to enable the userChrome.css settings by default.

<img width="871" height="707" alt="Image" src="https://github.com/user-attachments/assets/15e41595-ad93-44d1-a65a-841adfc33d12" />

<img width="812" height="495" alt="Image" src="https://github.com/user-attachments/assets/856513b4-057f-4944-966e-99324ad6e154" />

**Comment by stefanwimmer128** [comment]
Thanks. I didn't realize that you had to enable the setting by default to make it work at all.
