### ISSUE TITLE
[Bug]: Tab groups incorrectly shared across all workspaces

### ISSUE THREAD

**Issue by StanSvec** [Floorp-Projects/Floorp#1804]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When a tab group is created, it automatically appears in all workspaces instead of being limited to the one where it was created. This breaks expected workspace isolation.

### Reproduction Steps

1. Create a new **tab group** withing a workspace
2. Switch to a different workspace or create a new workspace
3. Observe that the newly created tab group is also visible in the new workspace

### Expected Behavior

Tab groups should only appear in the workspace where they were created, not in other workspaces.

### Actual Behavior

Tab groups appear in all workspaces, regardless of where they were created.

### Screenshots

Create a tab group:
<img width="801" alt="Image" src="https://github.com/user-attachments/assets/18adb400-f2bf-491c-91e6-7c3fcb5f3727" />
Create new workspace and observe the tab group being there too:
<img width="651" alt="Image" src="https://github.com/user-attachments/assets/5c0abf87-8405-4bbb-8262-5a59311532fe" />
 

### Browser Version

140.0@12.0.5 (aarch64)

### Operating System

macOS 15.5

**Comment by Ryosuke-Asano** [comment]
This issue will fixed at 12.0.17

**Comment by amogus07** [comment]
The problem still exists with Tree Style Tab. Is there any way to fix it?
