### ISSUE TITLE
[Bug]: Mouse gesture does NOT work correctly

### ISSUE THREAD

**Issue by nolnol0** [Floorp-Projects/Floorp#1842]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I customized several mouse gestures on the latest Floorp, but found some of them doesn't work correctly, also its gesture trail isn't smooth.

### Reproduction Steps

1. create several new mouse gesture
2. use these created gestures

<img width="1299" height="3245" alt="Image" src="https://github.com/user-attachments/assets/69d18775-f534-4dc0-a1bd-c709f5bcaf5a" />

### Expected Behavior

the gestures works well

### Actual Behavior

5 of these gestures don't work correctly. 
The gesture trail go on growing after I release the right mouse button when mouse gesture complete, press the right mouse button can interrupt its growing(left button can't interrupt).

another issue: its trail isn't smooth.

![Image](https://github.com/user-attachments/assets/9e25eace-14eb-4879-95c7-9edc60edb499)

### Screenshots

https://github.com/user-attachments/assets/bba68d6f-941a-49e1-956f-29db93346d31

### Browser Version

12.0.15

### Operating System

win 11 pro, 24H2, Operating system version 26100.3775, Experience Windows Function Experience Package 1000.26100.66.0

**Comment by Ryosuke-Asano** [comment]
Please forgive me, as the mouse gesture trails are the limit of my current abilities.
I will resolve all non-functional features at once.

**Comment by AndroidDeveloperLB** [comment]
Could this be related to keyboard shortcuts too?

I wanted to have "Reopen Closed Tab" that's mentioned here, but for a keyboard shortcut that I've customized to be a simple ALT+Z (similar to CTRL+Z for undo). For some reason this action is mentioned twice in the list, and it doesn't work for either of them...

**Comment by Ryosuke-Asano** [comment]
> Could this be related to keyboard shortcuts too?
> 
> I wanted to have "Reopen Closed Tab" that's mentioned here, but for a keyboard shortcut that I've customized to be a simple ALT+Z (similar to CTRL+Z for undo). For some reason this action is mentioned twice in the list, and it doesn't work for either of them...

YES

**Comment by nolnol0** [comment]
> Please forgive me, as the mouse gesture trails are the limit of my current abilities. I will resolve all non-functional features at once.
never mind the gesture trails, it's a minor issue and can be improved later. the non-functional features is the major issue.
thanks.

**Comment by Ryosuke-Asano** [comment]
Fixed！

**Comment by AndroidDeveloperLB** [comment]
@surapunoyousei Can't confirm about the keyboard shortcut I wanted to have:
ALT+Z for undo closed (called "Reopen Closed Tab" here: about:hub#/features/shortcuts ).

version: 142.0.2@12.1.4 (64-bit)

Please fix...

**Comment by SanyaIV** [comment]
The 12.4.0 update mentions fixing Reopen Closed Tab for mouse gestures however it's still not working for me on 12.4.0@144.0.2. What information can I provide to help identify and fix it?

One oddity is that I have two different "Reopen Closed Tab" in my dropdown of mouse gesture actions, neither of which work.

**Comment by Ryosuke-Asano** [comment]
WIP

**Comment by GoustiFruit** [comment]
Yeap, duplicates "Reopen Closed Tab", and none of them do work.

**Comment by AndroidDeveloperLB** [comment]
I think it got fixed
