### ISSUE TITLE
[Bug]: Floorp-Portable-v2 creates empty "Floorp" folders under %APPDATA%

### ISSUE THREAD

**Issue by bodayw** [Floorp-Projects/Floorp#1876]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

As the title suggests, Floorp-Portable-v2 now creates two empty "Floorp" folders upon running, under two %APPDATA% locations, respectively, e.g.:

C:\Users\username\AppData\Local
C:\Users\username\AppData\Roaming

### Reproduction Steps

1. Download the latest release of Floorp-Portable-v2
2. Run it

### Expected Behavior

Portable apps should not create folders/files outside its own directory

### Actual Behavior

(as suggested above)

### Screenshots

(don't think necessary)

### Browser Version

11.28.0 (currently the latest portable) and 12.0.15 (upgraded)

### Operating System

reproduced on Windows 10 22H2 and Windows 11 24H2

**Comment by Ryosuke-Asano** [comment]
We'll resarch this issue. Thanks

**Comment by Ryosuke-Asano** [comment]
https://github.com/Floorp-Projects/Floorp-Portable-v2/commit/af06d025f0f6cb6ed9557d9f4b7bb5f88a4f9c89

This issue will fixed at 12.0.17

**Comment by Ryosuke-Asano** [comment]
Fioxed

**Comment by bodayw** [comment]
Hi, unfortunately it seems the issue is not fixed on my end.

I just downloaded the latest portable version after manually deleted all of the old files/folders I could find. Shortly after running it for the first time I found these folders created:

C:\Users\[username]\AppData\Local\Floorp
C:\Users\[username]\AppData\Roaming\Floorp\Profile Groups

Again, all of them are empty.
