### ISSUE TITLE
[Bug]: Multi-row tabs do not appear in multiple rows

### ISSUE THREAD

**Issue by REALERvolker1** [Floorp-Projects/Floorp#1926]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Multi-row tabs do not appear in multiple rows anymore after I updated my Floorp flatpak installation (ID: `one.ablaze.floorp`) to `12.1.2`. They show a single row, but I have to scroll down to see the other rows, which in my opinion, defeats the entire purpose of a multi-row tab bar. I am concerned about this because it was very helpful in making me manage the amount of tabs I had open, and without this feature, I will have much more trouble keeping myself focused and organized.

### Reproduction Steps

1. move the directory `~/.var/app/one.ablaze.floorp` to `~/.var/app/one.ablaze.floorp-backup`, to reset all previous settings. The rest of the instructions assume the `LANG=en_US.UTF-8` system locale, so the specific names might be different for you.
2. click "Open New Tab", then click on the hamburger menu on the top right of the screen, underneath the X. From there, open "Settings"
3. click on "Floorp Hub", then click on "Tab & Appearance". Scroll down to "Tab Bar"
4. Click the dot that says "Multi-row". You should see the new tab "+" button snap to the right of the tab bar.
5. Close, then relaunch Floorp, to completely synchronize settings
6. Click the "+" button several times to open a large amount of new tabs. After a while, You should notice that new tabs do not appear to be created. However...
7. Scroll down to access your new tabs

### Expected Behavior

in lieu of a screenshot of the behavior of previous Floorp versions, please accept this UI mockup

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/ce631563-7d45-4446-8c34-c5f9fd4a64e2" />

### Actual Behavior

Technically this could be considered a "multi-row tab bar". However, the tabs do not show in multiple rows. Please refer to the screenshots section below for what I am referring to.

### Screenshots

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/86e7a730-e329-426c-accf-7a420ecde5e1" />

One scroll down later,

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9092e87a-3c5f-4da2-9b38-ee523b58eb8d" />

My settings

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9d8577a1-ff55-493a-9126-16a80262420d" />

### Browser Version

12.1.2

### Operating System

`Arch Linux x86_64`, using `Hyprland 0.50.1` (Wayland) on kernel `Linux 6.16.1-zen1-1-zen`

### Additional Context

This was the main reason I use Floorp instead of other browsers. Multi-row tabs were a wonderful feature that forced me to have good tab-managing habits. Some would definitely consider them annoying, but I found that "annoyance" very helpful and motivational.

**Comment by REALERvolker1** [comment]
Forgot to add, this is what my old-and-upgraded profile looks like with a ridiculous amount of new tabs. I believe this is a separate issue because my configurations are different, but you can imagine my shock upon opening my browser to find something like this instead of my usual tab rows.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/53f32586-4c16-4ea9-ab38-f9071312f7b5" />

**Comment by Ryosuke-Asano** [comment]
WIP

**Comment by ghost** [comment]
In my case, multi row mode causes freeze when I re-order the tabs since 12.1
On fedora wayland

**Comment by Ryosuke-Asano** [comment]
Fixed!

**Comment by ghost** [comment]
> Fixed!

Thank you for this update !
But, re-ordering multi lines tabs is still an issue : 
If you try to move a first line tab to a second or third line, it will not work :/

**Comment by Ryosuke-Asano** [comment]
As was the case with Floorp 11, I think implementing sorting will be difficult. I’ll do my best, though.

**Comment by ghost** [comment]
> As was the case with Floorp 11, I think implementing sorting will be difficult. I’ll do my best, though.

Re-ordoring was working on Floorp 11, in fact I am still with this version for now.

I found this : 
https://bugzilla.mozilla.org/show_bug.cgi?id=1714824#c0
In the last message a guy created a multi row script for firefox. Maybe it can helps ?

I understand it is a difficult task and I really hope a fix is possible. Multi row is something that make Floorp so unique and dragging a tab is something usual :)
