### ISSUE TITLE
[Bug]: Workspaces and Undo closed tab buttons resetting position after every restart

### ISSUE THREAD

**Issue by greeeen-dev** [Floorp-Projects/Floorp#2048]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When restarting Floorp, the placements of the Undo closed tab and Workspaces toolbar buttons reset to their default placements, even after changing their position or removing them from toolbars.

Additionally, this makes the Workspaces toolbar button basically unusable on vertical tabs, as it would be located in a toolbar which is only accessible when horizontal tabs are enabled.

### Reproduction Steps

1. Open Floorp
2. Move the Workspaces and Undo closed tab toolbar buttons
3. Restart Floorp

### Expected Behavior

Both buttons continue to respect user-defined placements across browser restarts.

### Actual Behavior

Both buttons reset to their default placements after every browser restart.

### Screenshots

<img width="616" height="131" alt="Image" src="https://github.com/user-attachments/assets/423a866b-00c9-4c4f-91c7-3ad889f8b018" />

Before restarting browser (both buttons have been removed from toolbar by me)

<img width="560" height="136" alt="Image" src="https://github.com/user-attachments/assets/e01c4b82-1c02-4dcc-8a68-e5c310419f1d" />

After restarting browser (both buttons return)

<img width="565" height="187" alt="Image" src="https://github.com/user-attachments/assets/8cabf524-eb52-491f-ba11-84a3718da40e" />

Vertical tabs enabled (notice the Workspaces toolbar button being missing, although it should be there)

<img width="1017" height="188" alt="Image" src="https://github.com/user-attachments/assets/eaab1a70-9bd2-4714-897e-a413355ee26f" />

Workspaces toolbar button is in the tabs toolbar, this toolbar is only visible on horizontal tabs

### Browser Version

12.3.1

### Operating System

macOS 26.0.1

**Comment by 9oOzv** [comment]
Started happening for me as well after updating to 12.3.1

**Comment by Ryosuke-Asano** [comment]
I'm researching this issue

**Comment by Bwopp** [comment]
Also happens to me on windows on 12.3.1

**Comment by Ryosuke-Asano** [comment]
This issue will fixed today

**Comment by greeeen-dev** [comment]
Workspaces button issue is fixed, undo closed tab button still keeps reappearing

**Comment by Bwopp** [comment]
Same here undo closed tab is still persisting and the workspaces button stays where it is placed now, however if it is removed it still reappears after a restart.

**Comment by clamitans** [comment]
Bloat it up some more! Force some more buttons on my screen! Time to uninstall this piece of shit browser.

**Comment by LFd3v** [comment]
It seems that "Undo Closed tab" button bug is fixed on v12.3.3 (Linux/GNOME).

**Comment by IsaacJ2** [comment]
Would like to mention the undo closed tab button still isn't working for me on Windows. I finally gave up and installed an extension that does it for me. Still using v12.3.3. Shift-ctl-t shortcut still works, though.

**Comment by LFd3v** [comment]
@IsaacJ2 This issue was about the "Undo Closed Tab" reappearing in the toolbar after is removed and the browser is restarted. If clicking on the button does not work but the shortcut does, then you may want to create a new issue. I can confirm that it does not work on v12.3.3 as well (Linux/GNOME).

**Comment by LFd3v** [comment]
@IsaacJ2 and anyone else that this may apply:
It seems that version v12.3.5 also fixed the "Undo Closed Tab" button not working.
