### ISSUE TITLE
[Bug]: Navigation bar 'bottom' renders address bar upside-down and mirrored at top of window

### ISSUE THREAD

**Issue by villainous-j** [Floorp-Projects/Floorp#2055]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When "Navigation position" is set to "bottom", the address bar renders upside-down, mirrored, and at the top of the window. Additionally, the minimize-maximize-close buttons are being duplicated to the bottom of the window:

<img width="1203" height="702" alt="Image" src="https://github.com/user-attachments/assets/197caa96-6846-4e9b-8f66-6762b3859db5" />

This is unfortunately almost impossible to use.

### Reproduction Steps

1. Set "Navigation position" to "bottom"
2. Save settings
3. Restart browser

### Expected Behavior

The address bar should be at the bottom, without the cloned minimize-maximize-close buttons.

### Actual Behavior

When "Navigation position" is set to "bottom", the address bar renders upside-down, mirrored, and at the top of the window. Additionally, the minimize-maximize-close buttons are being duplicated to the bottom of the window.

### Screenshots

<img width="1203" height="702" alt="Image" src="https://github.com/user-attachments/assets/225707ff-98c7-4b3e-93c7-bf12b4ea9692" />

### Browser Version

12.3.2

### Operating System

Windows 11

**Comment by Ryosuke-Asano** [comment]
Work in progress

**Comment by Ryosuke-Asano** [comment]
Fixed

**Comment by villainous-j** [comment]
hi @surapunoyousei, i'm still getting the duplicate of these buttons:

<img width="120" height="32" alt="Image" src="https://github.com/user-attachments/assets/118dc1e7-1e3b-4922-bb19-ced173a80e6d" />

<img width="1200" height="713" alt="Image" src="https://github.com/user-attachments/assets/c6ba6ca1-6830-4645-bfc5-ab5d0537f47d" />

but otherwise is looking improved!
