### ISSUE TITLE
[Bug]: Customize Toolbar is broken

### ISSUE THREAD

**Issue by LFd3v** [Floorp-Projects/Floorp#2065]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Since v12.3.2 (at least), the "Customize Toolbar..." option is glitchy, it shows a transparent window and has all sort of visual problems when trying to move/add/remove items.

~~But even if not used, the "Undo Closed Tab" is always present after the app is restarted, even if removed with "Remove from Toolbar" in its contextual menu.~~ (fixed in v12.3.3)

Tested with a new profile on v12.3.3.

### Reproduction Steps

a. Try to use "Customize Toolbar..." from the contextual menu of the toolbar or using the menu More tools > Customize menu

~~b. Remove "Undo Closed Tab" from the toolbar either by using its contextual menu or customizing the toolbar first and then dragging it off the toobar~~

### Expected Behavior

It should be possible to customize the toolbar without glitches, like it used to happen before v12.x.

### Actual Behavior

a. Many glitches in the customize toolbar window

~~b. "Undo Closed Tab" is shown in the toolbar everytime the browser is restarted, even after removing it.~~

### Screenshots

<img width="1024" height="784" alt="Image" src="https://github.com/user-attachments/assets/7e91aac1-adfa-4f28-9d30-69214478543e" />

PS: the window background looks black because it is showing the web page background here, below is a "screenshot of the screenshot open in an image viewer".

<img width="1024" height="837" alt="Image" src="https://github.com/user-attachments/assets/0180c85c-d583-4403-a38a-04d610c852d8" />

### Browser Version

v12.3.3

### Operating System

Linux/GNOME/Wayland

### Additional Context

N/A

**Comment by DoYouKnowMyNamePlz** [comment]
Unsure why "Undo Closed Tab" was crossed off but it is still an issue after every restart.

**Comment by LFd3v** [comment]
@DoYouKnowMyNamePlz For me it is fixed on v12.3.3: update, remove button, restart Floorp, button missing.

**Comment by DoYouKnowMyNamePlz** [comment]
> [@DoYouKnowMyNamePlz](https://github.com/DoYouKnowMyNamePlz) For me it is fixed on v12.3.3: update, remove button, restart Floorp, button missing.

it seems your right. It was re added after I Updated it, so I just assumed it was still happening.

**Comment by LFd3v** [comment]
@surapunoyousei Still not fixed on v12.3.5. Below is a screen recording when starting Floorp on XWayland (`MOZ_ENABLE_WAYLAND=0 floorp`), this was recorded on a brand new profile.

https://github.com/user-attachments/assets/6dd176ef-0ad1-440e-923a-0361648748ba

It is much worse under Wayland, I cannot show it using a screen recording simply because it will not record it (i.e. the recording shows no glitches), but basically what happens is that the background is transparent and there are visual glitches everywhere, like a trail when dragging things. On XWayland it does not have other visible glitches besides the transparent window background.

**Comment by LFd3v** [comment]
Looks like it is fixed in v12.4.0. Thank you.
