### ISSUE TITLE
[Bug]: Automatic Update is broken on Linux since v12.3.0

### ISSUE THREAD

**Issue by LFd3v** [Floorp-Projects/Floorp#2066]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I have the tarball installed for my user on Linux. Before v12.3.0, auto-update worked fine, but not anymore.

### Reproduction Steps

1. Download the tarball for Linux
2. Uncompress it to a folder
3. Create a .desktop file to launch Floorp
4. Get a notification in the app about the update or open Help > About Floorp when you know there is a new version

### Expected Behavior

The update will be downloaded and installed automatically after the browser is restarted.

### Actual Behavior

Download completes but then it shows an error and the update is not applied.

### Screenshots

N/A

### Browser Version

v12.3.2

### Operating System

Linux/GNOME/Wayland

### Additional Context

I have updated to v12.3.3 manually, I cannot test if it is still broken until a new version is released, of course.

**Comment by the51stater** [comment]
I can test this issue. I will stay on v12.3.1.

https://github.com/user-attachments/assets/a6616eda-67c6-4efd-906a-8dbcb776e457

<img width="686" height="67" alt="Image" src="https://github.com/user-attachments/assets/31123f1f-3e42-4eab-b9cb-25223d6c8008" />

**Comment by Ryosuke-Asano** [comment]
Please download from official page following instruction when Floorp says update failed. I fixed this issue at 12.3.3 

This issue is only happend on 12.3.2

**Comment by LFd3v** [comment]
@surapunoyousei I hope it is fixed in v12.3.3, but it was also present at least on v12.3.1 as shown above, not only v12.3.2. Regards.

**Comment by LFd3v** [comment]
@surapunoyousei
I am sorry, but it is still broken, at least when trying to update from v12.3.3 to v12.3.5 (I did not get any notification about v12.3.4 btw):

    out 27 09:19:01 floorp.desktop[1372511]: /home/user/Applications/floorp/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory

As a workaround, I used this in a terminal, while in the app directory:

    LD_LIBRARY_PATH=. ./floorp --class="floorp"

PS: I cannot re-open this issue, if required I can open a new one. Regards

**Comment by the51stater** [comment]
The error while loading shared libraries is another issue existing since the very first v12 version. Yes, the user need to manual set path before doing update.

12.3.1 / 12.3.2 had another updating issue about signature. That issue was fixed by 12.3.3 as @surapunoyousei said.

**Comment by LFd3v** [comment]
Update to v12.4.0 worked without issues. Thank you.

**Comment by Ryosuke-Asano** [comment]
Sorry. I saw your report, but I was so busy dealing with other bugs that I didn’t even have time to reply.
Thank you.
