### ISSUE TITLE
[Bug]: Navigation bar 'bottom' duplicates title bar buttons

### ISSUE THREAD

**Issue by villainous-j** [Floorp-Projects/Floorp#2085]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When "Navigation position" is set to "bottom", the title bar buttons are being duplicated to the bottom of the window. They should only render at the top of the window.

<img width="1200" height="713" alt="Image" src="https://github.com/user-attachments/assets/d9e64e11-4d89-4231-814c-78f0734cd976" />

### Browser Version

12.3.5

### Operating System

Windows 11

**Comment by abc16361** [comment]
In my case after updated to v.12.3.5 (on Windows 11), buttons of Bookmarks menu, Downloads and Extensions on Navigation Bar do not work anymore if Navigation Bar is set to Bottom. On click, Bookmarks menu doesn't show bookmark list of folders and bookmarks, and buttons Downloads and Extensions have no response. If Navigation Bar is set to Top, all these buttons work normal. I also tried it on all versions of 12.3.x, the errors are the same.

**Comment by EekaDroid** [comment]
> In my case after updated to v.12.3.5 (on Windows 11), buttons of Bookmarks menu, Downloads and Extensions on Navigation Bar do not work anymore if Navigation Bar is set to Bottom. On click, Bookmarks menu doesn't show bookmark list of folders and bookmarks, and buttons Downloads and Extensions have no response. If Navigation Bar is set to Top, all these buttons work normal. I also tried it on all versions of 12.3.x, the errors are the same.

The exact same thing is happening to me as well.

**Comment by Ryosuke-Asano** [comment]
I don’t think the issue with the duplicated window buttons has been fixed yet, but I believe the toolbar button functionality has been restored.

**Comment by abc16361** [comment]
> I don’t think the issue with the duplicated window buttons has been fixed yet, but I believe the toolbar button functionality has been restored.

Bookmarks menu and Downloads works again, but the Extensions is still the same.

**Comment by abc16361** [comment]
If the Extensions does not work on a bottomed toolbar, it has to set it back to "Top" before setting "Pin to Toolbar", and it seems there are no other ways to do that.
= Bottom =
<img width="506" height="455" alt="Image" src="https://github.com/user-attachments/assets/6baf12f2-cd8a-420b-96c2-c0330c7293b3" />
= Top =
<img width="689" height="618" alt="Image" src="https://github.com/user-attachments/assets/0f4a142d-cb50-4d82-8227-c3d0b292b2c9" />

**Comment by Ryosuke-Asano** [comment]
<img width="784" height="848" alt="Image" src="https://github.com/user-attachments/assets/5e3767d1-d391-49cd-a40f-9567526a699d" />

Hmm... We need more information.

**Comment by abc16361** [comment]
I am using Windows 11.  I just tested it again and have found out that, on bottom toolbar:
- if without any third party's extensions, clicking Extensions button would open Add-ons Manager, the same behavior as on top toolbar;
- with some third party's extensions, clicking Extensions button would open Add-ons Manager but not a popup add-on list;
- with some third party's extensions, clicking Extensions button gives no response, not even an opened Add-ons Manager.

I have tried them on a new profile and it gives the same result, so it has given me the impression that on bottom toolbar Extensions button fails to work normally or at least on my Windows 11.

== extensions not blocking Add-ons Manager open but no popup add-on list ==

<img width="550" height="747" alt="Image" src="https://github.com/user-attachments/assets/105332e6-6147-4317-bebf-e43eb43b37d3" />

== extensions blocking Add-ons Manager open and no popup add-on list ==
 
<img width="672" height="2519" alt="Image" src="https://github.com/user-attachments/assets/e9494966-c8e5-4b86-8559-d1b0af16b626" />

**Comment by villainous-j** [comment]
toolbar buttons are working for me in 12.4.0, on Windows 11. perhaps it would be best to open a new issue for your specific issue, @abc16361

**Comment by villainous-j** [comment]
Original issue with the duplicated buttons looks to be resolved in v12.6.0! Closing the issue.
