### ISSUE TITLE
[Bug] Wrong label for Install App icon

### ISSUE THREAD

**Issue by TheChilledBuffalo** [Floorp-Projects/Floorp#657]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Wrong tooltip when hovering over Install App button.

### To Reproduce

1. Hover over the install app icon.
2. You see the wrong label. Its given "ssb-page-actions".

### Expected behavior

It should be something like "Install App"

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/87632612/a69a77a4-4489-45da-9667-74ff509fce07)

### OS Info

Windows 11 23H2

### Floorp Version

11.7.1

**Comment by regularenthropy** [comment]
Should be fixed in this commit. 

https://github.com/Floorp-Projects/Unified-l10n-central/commit/4fe610a371d78c6fe38fecc0382a7dca4a800eaf

**Comment by surapunoyousei** [comment]
I'll fix it the commit, maybe not fix it...

**Comment by TheChilledBuffalo** [comment]
@regularenthropy thank you, but did not fix the issue. In fact, it made it worse.

![image](https://github.com/Floorp-Projects/Floorp/assets/87632612/118a9815-67b9-468e-a1cb-d1c715d5291e)

**Comment by regularenthropy** [comment]
> @regularenthropy thank you, but that did not fix the issue. In fact, it made it worse.
> 
> ![image](https://github.com/Floorp-Projects/Floorp/assets/87632612/118a9815-67b9-468e-a1cb-d1c715d5291e)
> 

OK. Its the CSS issue, so I'll adjust localization to temporarily fix the problem

**Comment by surapunoyousei** [comment]
Don't do that. I will fix it

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/33c26a2d-2ce7-4d06-b76a-6585e411a999)
