### ISSUE TITLE
[Bug] Collapsed Vertical Tab Bar Becomes Invisible When Expanded in 11.8.0

### ISSUE THREAD

**Issue by Akryllyk** [Floorp-Projects/Floorp#704]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When using the vertical tabs, when hovering over the tab bar its expands as normal, however it's transparent under the text/icons so it blurs with what's open. This also occurs even on a new profile and started happening after the update to 11.8.0.

### To Reproduce

1. Go to settings
2. Go to design
3. enable the vertical tab bar, and then make sure "collapse vertical tab bar" is selected. 
4. Issue should now be occuring 

### Expected behavior

The background of the vertical tab bar to expand out behind the tabs when hovered over. 

### Screenshots

![Floorp](https://github.com/Floorp-Projects/Floorp/assets/32924995/debca3cc-cf31-42ce-97b7-536707dc594b)

### OS Info

Windows 11 23H2, OS Build 22631.3007

### Floorp Version

11.8.0

**Comment by hisamafahri** [comment]
+1 experiencing the same issue

**Comment by surapunoyousei** [comment]
Maybe only occured at macOS..?

**Comment by TheChilledBuffalo** [comment]
> Maybe only occured at macOS..?

I can see it on Linux as well.

**Comment by surapunoyousei** [comment]
Odd

**Comment by surapunoyousei** [comment]
@creeper-0910 なんかやってなかったっけ

**Comment by surapunoyousei** [comment]
OK. I found the reason. This PR change z-index.

 https://github.com/Floorp-Projects/Floorp-core/pull/13

**Comment by surapunoyousei** [comment]
Fixed.

**Comment by LeonardoMantovani** [comment]
Is it possible that I'm still experiencing the issue? 
(Windows 11, Floorp 11.8.2, **light theme**. With Dark theme the background of the expanded vertical tab bar is not transparent and works as expected)

**Comment by hisamafahri** [comment]
+1. Works as expected in the dark theme, but still occurs in the light theme.

**Comment by surapunoyousei** [comment]
A... Give me screenshot

**Comment by surapunoyousei** [comment]
Ahhh.. I reproduced.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by LeonardoMantovani** [comment]
Any idea about approximately when the next release with the fix will be shipped?

**Comment by surapunoyousei** [comment]
Next Tuesday

**Comment by 0xDkXy** [comment]
I noticed this bug was announced fixed in the release version 11.9.0. But I still encountered this bug in the v11.10.2

![image](https://github.com/Floorp-Projects/Floorp/assets/55947248/2bf12ef2-d89f-4200-9ecf-9d4bbeda6de2)

**Comment by creeper-0910** [comment]
Does it only happen when the vertical tab bar is to the right?

**Comment by 0xDkXy** [comment]
> Does it only happen when the vertical tab bar is to the right?

No, the left also had this problem.

![20240304_15h09m18s_grim](https://github.com/Floorp-Projects/Floorp/assets/55947248/a5b137a7-35cf-4a16-bb8f-05dfae389e7a)

**Comment by TheChilledBuffalo** [comment]
There is a PR open #973 that could potentially fix this.

**Comment by creeper-0910** [comment]
Ah, I didn't test it on linux, sorry.
I will check the PR.

**Comment by nabeelio** [comment]
I'm also seeing this on OSX, along with a darkey grey border showing up on top

![image](https://github.com/Floorp-Projects/Floorp/assets/99736/ff773f9c-3d42-478d-b3c0-5fda1cd9aaed)

**Comment by hesham-ayad** [comment]
Still seeing this on v.11.10.5 / flatpak / fedora 39

![image](https://github.com/Floorp-Projects/Floorp/assets/124933911/434c8264-462c-46e8-8053-f7a0026021d6)

**Comment by surapunoyousei** [comment]
I fixed this issue.

**Comment by y1zhou** [comment]
> I fixed this issue.

Still experiencing the same issue in v11.11.2 on macOS Sonoma 14.4.1. The text spans out but the background only expands slightly.

**Comment by Minnona** [comment]
Still happening on v11.13.0
![image](https://github.com/Floorp-Projects/Floorp/assets/23418072/540b4b3b-f121-4644-ae78-099308853a55)

**Comment by rongpengli** [comment]
<img width="264" alt="图片" src="https://github.com/user-attachments/assets/1b4d8fe8-3cce-4064-9ab9-74701117c8e9">
Hi, I am still suffering from this issue on V 11.15 the macOS 12 light theme. Dark theme works normally.

**Comment by blankspace** [comment]
![图片](https://github.com/user-attachments/assets/c18a6cab-6f45-4036-9944-a18eb993c3cb)

I'm experiencing the same issue in the beta version.

Floorp beta build: v11.17.0 | 20240810090147
Windows 11 23H2

**Comment by absol-0359** [comment]
This issue has also been reproduced on Floorp 11.17.1, Windows 11 23H2 22631.4037.
The following two patterns have been confirmed:
- When a theme other than the default is applied
- When the default theme is used and the window is inactive
https://github.com/user-attachments/assets/00a51187-832b-4c02-a0e4-48a4121daee7

**Comment by surapunoyousei** [comment]
currently, i'm working for fix this issue.

**Comment by absol-0359** [comment]
I have confirmed that this has been fixed in 11.17.3.

**Comment by absol-0359** [comment]
I am very sorry, but it appears that this issue still occurs with Firefox Proton Design and Floorp Fluerial Design.

![image](https://github.com/user-attachments/assets/488d1315-4da2-4252-b466-a8fd63789864)
