### ISSUE TITLE
Scroll bar still unscrollable in vertical mode in the latest v11.8.1

### ISSUE THREAD

**Issue by Plexprofile** [Floorp-Projects/Floorp#728]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

![bug](https://github.com/Floorp-Projects/Floorp/assets/139643082/68f31660-5abf-48c8-b8e6-698542eb65cc)
When using vertical tabs in the app, dragging the scrollbar does not scroll between tabs. Instead, it moves the entire app window up.

### To Reproduce

click and move the scroll bar in vertical move

### Expected behavior

scroll the tabs

### Screenshots

<img width="860" alt="image_33" src="https://github.com/Floorp-Projects/Floorp/assets/139643082/cb0d7602-4640-443f-8f7a-8a0b6f0564d3">

### OS Info

Win10 21h2

### Floorp Version

v11.8.1

**Comment by Plexprofile** [comment]
![bug](https://github.com/Floorp-Projects/Floorp/assets/139643082/7a9845ce-e03c-4e20-95b5-2f9ded08e826)

**Comment by surapunoyousei** [comment]
Did you enable auto extend at hover vertical tab bar？

**Comment by Plexprofile** [comment]
I guess not? 
<img width="863" alt="image_34" src="https://github.com/Floorp-Projects/Floorp/assets/139643082/5b7f3636-cb5b-4328-8ec7-54c69022b483">
<img width="644" alt="image_35" src="https://github.com/Floorp-Projects/Floorp/assets/139643082/54a35884-c9cf-447c-9a80-a9af2c4d09b3">

**Comment by surapunoyousei** [comment]
Hmm.... OK.

**Comment by surapunoyousei** [comment]
Ok. try Daylight channel build (https://github.com/Floorp-Projects/Floorp/releases/tag/beta). I fixed this issue

**Comment by jgdye** [comment]
I'm still having this issue on the latest Daylight channel. Windows only, Linux works fine on the stable channel.
