### ISSUE TITLE
[Bug] Elements not aligned properly when using the vertical tab bar

### ISSUE THREAD

**Issue by pranavajk1** [Floorp-Projects/Floorp#740]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The elements in the vertical tab bar are not aligned properly when the tab bar is collapsed. It looks a bit weird. 
![image](https://github.com/Floorp-Projects/Floorp/assets/114953548/cf90e3b3-4749-4577-8952-9d7842614346)

The plus icon at the bottom of the bar does is not aligned. (Can be disabled instead since there is already an option to add tab above).

The sound icon when playing a youtube video looks weird and is partially cut off when the tab is collapsed.

### To Reproduce

1. Enable the vertical tab bar.
2. Open a few tabs including youtube.
3. Collapse the vertical tab bar.
4. The icons are not aligned properly.

### Expected behavior

The icons should be aligned properly.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/114953548/ab37546d-79fd-4e4b-96a2-c173a5621dce)

### OS Info

Windows 11 23H2

### Floorp Version

11.8.1

**Comment by surapunoyousei** [comment]
Ahh. You use "Collapse Vertical Tab Bar". It's expected.

**Comment by pranavajk1** [comment]
The same looks a lot better in Microsoft Edge, so I think it can be improved further. As you can see in the screenshots, the icons are aligned better, and looks better in my opinion.

![image](https://github.com/Floorp-Projects/Floorp/assets/114953548/4813b419-a5a2-4fcf-aaf3-2fa9554b3caa)
![image](https://github.com/Floorp-Projects/Floorp/assets/114953548/8d37c531-043b-4adf-8ec2-35d38586b9c7)

**Comment by surapunoyousei** [comment]
You can submit this request to discussion.

**Comment by TheChilledBuffalo** [comment]
@pranavajk1 you could try using Firefox Proton UI instead of the others if that works for you. The alignments in vertical tab bar are perfect when you use that.

**Comment by creeper-0910** [comment]
It will probably be fixed by the next version.

**Comment by creeper-0910** [comment]
> ### Attention!
> 
>     * [x]  I understand that Floorp is NOT supported on Windows 7/8.1 or lower.
> 
> 
> ### Describe the bug
> 
> The elements in the vertical tab bar are not aligned properly when the tab bar is collapsed. It looks a bit weird. ![image](https://private-user-images.githubusercontent.com/114953548/298187578-cf90e3b3-4749-4577-8952-9d7842614346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzQwMzMsIm5iZiI6MTcwNTczMzczMywicGF0aCI6Ii8xMTQ5NTM1NDgvMjk4MTg3NTc4LWNmOTBlM2IzLTQ3NDktNDU3Ny04OTUyLTlkNzg0MjYxNDM0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwNjU1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTBjMGVhYTNiZGJiYTg1OTU5MDFkM2RmNDdiZWNiMjQ3YTNiMzNiNGJhM2Q4YjQ4OWMyNzA1M2JmYTc1NGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lLEHAV4umsXxeNZ6SoaH-XICnooOJSTS3ogGOmg-Lss)
> 
> The plus icon at the bottom of the bar does is not aligned. (Can be disabled instead since there is already an option to add tab above).
> 
> The sound icon when playing a youtube video looks weird and is partially cut off when the tab is collapsed.
> ### To Reproduce
> 
>     1. Enable the vertical tab bar.
> 
>     2. Open a few tabs including youtube.
> 
>     3. Collapse the vertical tab bar.
> 
>     4. The icons are not aligned properly.
> 
> 
> ### Expected behavior
> 
> The icons should be aligned properly.
> ### Screenshots
> 
> ![image](https://private-user-images.githubusercontent.com/114953548/298188084-ab37546d-79fd-4e4b-96a2-c173a5621dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzQwMzMsIm5iZiI6MTcwNTczMzczMywicGF0aCI6Ii8xMTQ5NTM1NDgvMjk4MTg4MDg0LWFiMzc1NDZkLTc5ZmQtNGU0Yi05NmEyLWMxNzNhNTYyMWRjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwNjU1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjg3M2QwOTNiNzFiYThjOWRiZTlhMDk3MzhkNjQ4MDZmOWE3MzkyMzg3ODEwNTllM2UxYTU5MWM2MmJlNjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ty9w8Y-T1x1l9aqsuiiL5ZjWzYnUFf7X9cMzQQqUpTA)
> ### OS Info
> 
> Windows 11 23H2
> ### Floorp Version
> 
> 11.8.1
> ### Additional context
> 
> _No response_

What theme are you using?

**Comment by creeper-0910** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/56744841/a029bfc8-6082-4122-867f-916551813aa0)
Fixed!

**Comment by TheChilledBuffalo** [comment]
@creeper-0910 Has the change been committed? Because I still can't see it in my dev build.

![image](https://github.com/Floorp-Projects/Floorp/assets/87632612/58b370b3-8f87-486d-9af4-5d6b3242c462)

**Comment by creeper-0910** [comment]
I am out of town and will commit when I return.

**Comment by creeper-0910** [comment]
I pushed, but some parts may be a little out of position.

**Comment by TheChilledBuffalo** [comment]
Yup saw your commit! A major part of the issue has been fixed. I did notice some minor issues with alignment here and there, which I'll try and fix if I get time.
