### ISSUE TITLE
[Bug] Google Meet can't access camera or microphone after floop v11.8.1

### ISSUE THREAD

**Issue by clementpoiret** [Floorp-Projects/Floorp#766]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

On v11.8.0, Google Meet was working as expected.
After v11.8.1, Google Meet shows that my mircrophone and camera are being blocked.
However, both are authorized. On other websites, such as Zoom, everything works as expected.
I am a Linux user on Wayland.

### To Reproduce

1. Go on https://meet.google.com,
2. Start a meeting,
3. Authorize both mic and cam,
4. It doesn't work :(

### Expected behavior

Both cam and mic working on google meet, as on other websites. 

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/10899984/6b9f5a71-58db-4192-92da-330c2794b5cd)

### OS Info

Arch Linux, Hyprland DE

### Floorp Version

11.8.1

### Additional context

I alse tried changing the User Agent, without success

**Comment by clementpoiret** [comment]
Fixed by v11.8.2, sorry for the spam :)

**Comment by krautschaedel** [comment]
I am still having this issue on 11.8.2, using Arch Linux with X11.

**Comment by clementpoiret** [comment]
Actually, I disappears

**Comment by clementpoiret** [comment]
Actually it disappeared after the upgrade, but reappeared just after. From my superficial investigation, it comes from the privacy.resistFingerprint options, or at least the user.js.

From `Customize Floorp with user.js`, I switched from to `Yokoffing Securefox` and re-enabled privacy.resistFingerprint in `about:config` and it seemed to solve the issue. Unfortunately, I did identified the exact setting that messed with Google Meet...

**Comment by clementpoiret** [comment]
It certainly is not a good solution, but could you try the following setting?

`user_pref("privacy.resistFingerprinting.exemptedDomains", "*.example.invalid, meet.google.com");`

**Comment by clementpoiret** [comment]
Related issue just for reference: https://www.reddit.com/r/LibreWolf/comments/19amlmf/google_meet_no_longer_able_to_use_camera_or_mic/

Maybe it simply came from and update of the firefox ESR base?

**Comment by surapunoyousei** [comment]
I still don't like the idea of making changes via user.js, as it may corrupt the browser.

Thus, I end up spending more time on advanced user customization, which results in less time for Floorp development and degradation of Floorp.

I kept considering changing the default settings, but this issue has made me decide not to do so.
