### ISSUE TITLE
[Bug]: Sidebar panels focus issue

### ISSUE THREAD

**Issue by Axenide** [Floorp-Projects/Floorp#950]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hi, I don't really know if this is a bug or if I should open a feature request, sorry if this is not the place.
When opening a sidebar panel, the focus stays on the page I already am until I click inside the panel. When I close the panel, if it is focused, the focus stays inside the panel. This happens both by clicking on it's icon or using keyboard shortcuts.

### Reproduction Steps

1. Open a sidebar panel
2. Focus stays in your already open page

### Expected Behavior

Opening a panel should focus it's content, and closing it should focus the page you are in.

### Actual Behavior

Panel and your current page aren't focused until you click inside them.

### Screenshots

-

### Browser Version

Mozilla Floorp 11.10.2

### Operating System

Arch Linux

**Comment by surapunoyousei** [comment]
Fixed

**Comment by Axenide** [comment]
Hi, sorry to reopen this but I'm on Floorp 11.11.2 and this isn't fixed, though I see a difference.
Now when a panel is closed, it still has focus so if you start hitting keys and stuff, those things will happen inside the panel even if you can't see it.
